name: Auto Deploy live.txt to GitHub Pages

# 触发条件：只有 live.txt 变化时才触发
on:
  push:
    branches:
      - main
    paths:
      - 'live.txt'       # 只监听 live.txt 文件变化
  workflow_dispatch:     # 可手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 检出仓库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ 配置 Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    # 3️⃣ 部署 live.txt 到 GitHub Pages
    - name: Deploy live.txt
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages     # GitHub Pages 分支
        publish_dir: ./              # 根目录
        keep_files: true             # 保留其他文件
        allow_empty_commit: true     # 即使没有变化也提交

    # 4️⃣ 输出访问链接
    - name: Show URL
      run: echo "✅ Your live.txt is available at: https://talibantv.byun.nyc.mn/live.txt"
