name: Hotel IPTV 更新

on:
  schedule:
    # 每天 8:00, 16:00, 0:00 北京时间
    - cron: "0 0,8,16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-hotel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update_hotel_live.py
        run: |
          if [ -f update_hotel_live.py ]; then
              python update_hotel_live.py
          else
              echo "❌ update_hotel_live.py 不存在"
              exit 1
          fi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add hotel.txt hotel_grouped.txt || echo "文件不存在，跳过"
          git commit -m "定时更新 Hotel IPTV [skip ci]" || echo "无变化，跳过 commit"
          git push || echo "推送失败"
