name: Hotel IPTV 更新

on:
  schedule:
    # 北京时间 0:00, 8:00, 16:00 对应 UTC 16:00, 0:00, 8:00
    - cron: "0 16,0,8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-hotel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update_hotel_live.py
        run: |
          if [ -f update_hotel_live.py ]; then
              python3 update_hotel_live.py
          else
              echo "❌ update_hotel_live.py 不存在"
              exit 1
          fi

      - name: List generated files
        run: ls -la "专区"

      - name: Commit & Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          commit_message: "定时更新 4K 直播源 [skip ci]"
          force: true
          file_pattern: "专区/4K.txt"
