name: Auto Update Hotel IPTV IP

on:
  workflow_dispatch:
  schedule:
    - cron: "5 2 * * *"   # 每天 2:05

jobs:
  iptv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run Update Hotel IPTV IP
        run: python main.py --type hotel --ip   # 根目录 main.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto Update IPTV IP"
          branch: main
          file_pattern: "outputs/**, txt/**, *.txt, *.m3u"
          push_options: "--force"
