name: 'Daily Job'

on:
  schedule:
    - cron: '0 20 * * *' # 每天 20:00 UTC
  workflow_dispatch:

jobs:
  run_daily_job:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencc-python-reimplemented

      # 4️⃣ 运行 Python 脚本
      - name: Run Python script
        run: python main.py

      # 5️⃣ 提交更改
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github_actions[bot]"
          git add -A
          TZ='Asia/Shanghai' git commit -m ":tada: Daily AutoUpdate $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

      # 6️⃣ 推送（先 rebase，失败就强制推送）
      - name: Push changes
        run: |
          git pull --rebase origin main || echo "Rebase failed, will try force push"
          git push origin main || git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
