name: Update CCTV Live

on:
  schedule:
    # 每两小时运行一次
    - cron: '0 */2 * * *'
  workflow_dispatch:  # 手动触发

jobs:
  update-cctv:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm

      # 4. 运行爬取脚本
      - name: Run scrape_cctv.py
        run: python scripts/scrape_cctv.py --output cctv.txt

      # 5. 提交并推送更新
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cctv.txt
          git diff-index --quiet HEAD || git commit -m "Update CCTV live sources"
          git push
