name: Scrape CCTV Live Streams

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: {}

concurrency:
  group: scrape-cctv
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scripts/scrape_cctv.py --output-dir output --timeout 10

      - name: Show generated file
        run: |
          echo "=== output/cctv.txt ==="
          sed -n '1,200p' output/cctv.txt || true

      - name: Commit and push generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/cctv.txt || true
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "自动更新 CCTV 直播源: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || true
            git push origin HEAD:${{ github.ref_name }} || true
          else
            echo "No changes to commit."
          fi
