name: Sync Files to Cloudflare R2

on:
  schedule:
    - cron: '10 0 * * *'  # UTC 时间每天 00:10
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout the repository
        uses: actions/checkout@v2

      # 2️⃣ 安装 rclone
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      # 3️⃣ 配置 rclone remote
      - name: Configure rclone with Cloudflare R2
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          rclone config create cloudflare_r2 s3 \
            provider "Other" \
            env_auth "false" \
            access_key_id "${R2_ACCESS_KEY_ID}" \
            secret_access_key "${R2_SECRET_ACCESS_KEY}" \
            endpoint "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" \
            location "auto" \
            acl "private"

      # 4️⃣ 检查本地文件
      - name: Check local live.txt
        run: |
          if [ -f ./live.txt ]; then
            echo "Found live.txt:"
            ls -lh ./live.txt
          else
            echo "Error: live.txt not found!" 
            exit 1
          fi

      # 5️⃣ 检查远程 R2 桶
      - name: Check R2 bucket
        run: |
          echo "Listing R2 bucket root:"
          rclone lsd cloudflare_r2:

      # 6️⃣ 上传文件
      - name: Upload live.txt to Cloudflare R2
        run: |
          echo "Uploading live.txt as DailyTV.txt to Cloudflare R2..."
          rclone copyto ./live.txt cloudflare_r2:optimization/DailyTV.txt
          echo "Upload complete."
