name: Sync live.txt to Cloudflare R2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Upload live.txt to R2
        shell: bash
        run: |
          if [ ! -f ./live.txt ]; then
            echo "错误：本地文件 live.txt 不存在，上传失败！"
            exit 1
          fi

          echo "开始上传 live.txt 到 R2 桶 bxtv..."

          rclone copy ./live.txt s3:bxtv/DailyTV.txt \
            --s3-provider Minio \
            --s3-endpoint https://f0f6bddeda81f13cec09327818e9348b.r2.cloudflarestorage.com \
            --s3-access-key-id ${{ secrets.R2_ACCESS_KEY }} \
            --s3-secret-access-key ${{ secrets.R2_SECRET_KEY }} \
            --s3-region auto \
            --progress

          echo "上传完成 ✅"
