name: Sync Files to Cloudflare R2

on:
  schedule:
    - cron: '10 0 * * *'  # 每天 UTC 00:10 自动运行
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Configure rclone with Cloudflare R2
      env:
        R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      run: |
        rclone config create cloudflare_r2 s3 provider "Other" env_auth "false" \
          access_key_id "${R2_ACCESS_KEY_ID}" \
          secret_access_key "${R2_SECRET_ACCESS_KEY}" \
          endpoint "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

    - name: Check live.txt content
      run: |
        echo "=== 文件信息 ==="
        ls -lh ./live.txt
        echo "=== 文件前10行内容预览 ==="
        head -n 10 ./live.txt || echo "live.txt 是空的"

    - name: Upload live.txt as DailyTV.txt
      run: |
        echo "=== 上传到 bxtv/DailyTV.txt ==="
        rclone copyto ./live.txt cloudflare_r2:bxtv/DailyTV.txt --progress --ignore-times -vv
