name: Auto Sync Live Sources to Cloudflare R2

on:
  push:
    branches:
      - main  # 仓库 main 分支有更新就触发
  workflow_dispatch:  # 可手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Merge all live source files into DailyTV.txt
      run: |
        # 清空旧文件
        > DailyTV.txt
        # 找出所有 m3u/m3u8/txt 文件并按文件名排序合并
        find . -type f \( -name "*.m3u" -o -name "*.m3u8" -o -name "*.txt" \) | sort | while read file; do
          cat "$file" >> DailyTV.txt
          echo "" >> DailyTV.txt
        done
        echo "Merged all live sources into DailyTV.txt"

    - name: Configure rclone with Cloudflare R2
      env:
        R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      run: |
        rclone config create cloudflare_r2 s3 \
          provider "Other" \
          env_auth "false" \
          access_key_id "${R2_ACCESS_KEY_ID}" \
          secret_access_key "${R2_SECRET_ACCESS_KEY}" \
          endpoint "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" \
          location "auto" \
          acl "private"

    - name: Upload DailyTV.txt to R2
      run: |
        rclone copy ./DailyTV.txt cloudflare_r2:optimization/DailyTV.txt --progress
