name: Upload live.txt to Cloudflare R2

on:
  push:
    paths:
      - live.txt   # 只在 live.txt 变动时触发
  workflow_dispatch: # 手动触发

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Upload live.txt to R2
        env:
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
          R2_ENDPOINT: https://f0f6bddeda81f13cec09327818e9348b.r2.cloudflarestorage.com
          BUCKET: bxtv
          OBJECT: DailyTV.txt
        run: |
          FILE="./live.txt"
          if [ ! -f "$FILE" ]; then
            echo "$FILE 不存在，上传终止"
            exit 1
          fi

          echo "配置临时 rclone remote..."
          rclone config create tmp_cloudflare s3 \
            provider Minio \
            access_key_id "$R2_ACCESS_KEY" \
            secret_access_key "$R2_SECRET_KEY" \
            endpoint "$R2_ENDPOINT" \
            region auto \
            acl private \
            --non-interactive

          echo "开始上传 $FILE 到 R2 桶 $BUCKET/$OBJECT ..."
          for i in 1 2 3; do
            if rclone copy "$FILE" tmp_cloudflare:"$BUCKET/$OBJECT" --progress; then
              echo "上传成功 ✅"
              # 删除临时 remote
              rclone config delete tmp_cloudflare
              exit 0
            else
              echo "上传失败，第 $i 次重试..."
              sleep 3
            fi
          done

          echo "上传失败 ❌，请检查 endpoint、桶名、Access Key 和 Secret Key 是否正确"
          rclone config delete tmp_cloudflare
          exit 1
