name: Upload live.txt to Cloudflare R2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Upload live.txt to R2
        env:
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
        run: |
          FILE=./live.txt
          BUCKET=bxtv
          OBJECT=DailyTV.txt
          ENDPOINT="https://f0f6bddeda81f13cec09327818e9348b.r2.cloudflarestorage.com"

          if [ ! -f "$FILE" ]; then
            echo "$FILE 不存在，上传终止"
            exit 1
          fi

          echo "开始上传 $FILE 到 R2 桶 $BUCKET/$OBJECT ..."

          # 创建临时 rclone remote
          rclone config create tmp_cloudflare s3 \
            provider Minio \
            access_key_id "$R2_ACCESS_KEY" \
            secret_access_key "$R2_SECRET_KEY" \
            endpoint "$ENDPOINT" \
            region auto \
            acl private \
            --non-interactive

          # 上传文件
          rclone copy "$FILE" tmp_cloudflare:"$BUCKET/$OBJECT" --progress
          echo "上传完成 ✅"
