name: Sync Files to Cloudflare R2

on:
  schedule:
    - cron: '10 0 * * *'  # UTC 时间每天 00:10
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Configure rclone with Cloudflare R2
      env:
        R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      run: |
        rclone config create cloudflare_r2 s3 \
          provider "Other" \
          env_auth "false" \
          access_key_id "${R2_ACCESS_KEY_ID}" \
          secret_access_key "${R2_SECRET_ACCESS_KEY}" \
          endpoint "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" \
          location "auto" \
          acl "private"

    - name: Sync live.txt to Cloudflare R2
      run: |
        # 上传 live.txt 到 R2，并命名为 DailyTV.txt
        rclone copy ./live.txt cloudflare_r2:optimization/DailyTV.txt --progress --update
