name: Upload live.txt to Cloudflare R2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Upload live.txt to R2
      env:
        R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
        R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
        R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        R2_BUCKET: ${{ secrets.R2_BUCKET }}
      run: |
        FILE="./live.txt"

        if [ ! -f "$FILE" ]; then
          echo "本地文件 $FILE 不存在，上传失败 ❌"
          exit 1
        fi

        echo "配置临时 rclone remote..."
        rclone config create tmp_cloudflare s3 \
          provider Minio \
          access_key_id "$R2_ACCESS_KEY" \
          secret_access_key "$R2_SECRET_KEY" \
          endpoint "$R2_ENDPOINT" \
          region auto \
          acl private \
          --non-interactive

        echo "开始上传 $FILE 到 R2 桶 $R2_BUCKET/DailyTV.txt ..."
        RETRY=0
        MAX_RETRY=3
        until [ $RETRY -ge $MAX_RETRY ]
        do
          if rclone copy "$FILE" tmp_cloudflare:"$R2_BUCKET"/DailyTV.txt --progress; then
            echo "上传成功 ✅"
            break
          else
            RETRY=$((RETRY+1))
            echo "上传失败 ❌，第 $RETRY 次重试..."
            sleep 5
          fi
        done

        if [ $RETRY -eq $MAX_RETRY ]; then
          echo "上传失败，超过最大重试次数 ❌"
          exit 1
        fi

        echo "删除临时 rclone remote..."
        rclone config delete tmp_cloudflare
