name: Sync live.txt to Cloudflare R2

on:
  push:
    branches:
      - main        # 每次 push main 分支触发
  schedule:
    - cron: '10 0 * * *'  # 每天 UTC 00:10 自动触发
  workflow_dispatch:       # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Upload live.txt to R2
        run: |
          # 设置 R2 密钥
          export R2_ACCESS_KEY="${{ secrets.R2_ACCESS_KEY }}"
          export R2_SECRET_KEY="${{ secrets.R2_SECRET_KEY }}"

          # 使用 S3 backend URL 直接上传文件到 R2 桶 bxtv，命名为 DailyTV.txt
          rclone copy ./live.txt \
            "s3://${R2_ACCESS_KEY}:${R2_SECRET_KEY}@bxtv/DailyTV.txt?endpoint=https://f0f6bddeda81f13cec09327818e9348b.r2.cloudflarestorage.com&region=auto" \
            --progress
