name: Update CCTV M3U

on:
  schedule:
    # 每天北京时间早上 6 点运行（GitHub 用 UTC，要减去 8 小时）
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        run: python cctv_scraper.py

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add cctv.m3u
          git commit -m "更新 CCTV 直播源 $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
