name: Update IPTV

on:
  workflow_dispatch:   # 手动触发
  schedule:
    # 北京时间 9:00、17:00、01:00，转换为 UTC
    - cron: '0 1,9,17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3️⃣ 缓存 pip 依赖
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ 安装依赖
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium requests futures eventlet pytz opencv-python beautifulsoup4 translate lxml

      # 5️⃣ 运行 Python 脚本
      - name: Run IPTV scripts
        run: |
          echo ">>> 开始运行 iptv_udp.py"
          python ${{ github.workspace }}/iptv_udp.py
          echo ">>> 完成 iptv_udp.py"
          echo ">>> 开始运行 txt_m3u.py"
          python ${{ github.workspace }}/txt_m3u.py
          echo ">>> 完成 txt_m3u.py"

      # 6️⃣ 提交生成的文件
      - name: Commit and push generated files
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "your_name"
          # 只添加生成文件
          git add IPTV_UDP.txt IPTV_UDP.m3u outfiles/*.txt
          git commit -m "Update IPTV files" || echo "No changes to commit"
          git pull --rebase
          git push
